interface ThemeColors {
  primary: string;
  primaryHover: string;
  primaryLight: string;
  primaryDark: string;
  secondary: string;
  secondaryHover: string;
  secondaryLight: string;
  secondaryDark: string;
  accent: string;
  accentHover: string;
  accentLight: string;
  accentDark: string;
  background: string;
  backgroundSecondary: string;
  backgroundTertiary: string;
  surface: string;
  surfaceHover: string;
  surfaceActive: string;
  text: string;
  textSecondary: string;
  textTertiary: string;
  textInverse: string;
  border: string;
  borderHover: string;
  borderFocus: string;
  success: string;
  successLight: string;
  successDark: string;
  error: string;
  errorLight: string;
  errorDark: string;
  warning: string;
  warningLight: string;
  warningDark: string;
  info: string;
  infoLight: string;
  infoDark: string;
}

export const getThemeColors = (): ThemeColors => ({
  primary: process.env.NEXT_PUBLIC_COLOR_PRIMARY!,
  primaryHover: process.env.NEXT_PUBLIC_COLOR_PRIMARY_HOVER!,
  primaryLight: process.env.NEXT_PUBLIC_COLOR_PRIMARY_LIGHT!,
  primaryDark: process.env.NEXT_PUBLIC_COLOR_PRIMARY_DARK!,
  secondary: process.env.NEXT_PUBLIC_COLOR_SECONDARY!,
  secondaryHover: process.env.NEXT_PUBLIC_COLOR_SECONDARY_HOVER!,
  secondaryLight: process.env.NEXT_PUBLIC_COLOR_SECONDARY_LIGHT!,
  secondaryDark: process.env.NEXT_PUBLIC_COLOR_SECONDARY_DARK!,
  accent: process.env.NEXT_PUBLIC_COLOR_ACCENT!,
  accentHover: process.env.NEXT_PUBLIC_COLOR_ACCENT_HOVER!,
  accentLight: process.env.NEXT_PUBLIC_COLOR_ACCENT_LIGHT!,
  accentDark: process.env.NEXT_PUBLIC_COLOR_ACCENT_DARK!,
  background: process.env.NEXT_PUBLIC_COLOR_BACKGROUND!,
  backgroundSecondary: process.env.NEXT_PUBLIC_COLOR_BACKGROUND_SECONDARY!,
  backgroundTertiary: process.env.NEXT_PUBLIC_COLOR_BACKGROUND_TERTIARY!,
  surface: process.env.NEXT_PUBLIC_COLOR_SURFACE!,
  surfaceHover: process.env.NEXT_PUBLIC_COLOR_SURFACE_HOVER!,
  surfaceActive: process.env.NEXT_PUBLIC_COLOR_SURFACE_ACTIVE!,
  text: process.env.NEXT_PUBLIC_COLOR_TEXT!,
  textSecondary: process.env.NEXT_PUBLIC_COLOR_TEXT_SECONDARY!,
  textTertiary: process.env.NEXT_PUBLIC_COLOR_TEXT_TERTIARY!,
  textInverse: process.env.NEXT_PUBLIC_COLOR_TEXT_INVERSE!,
  border: process.env.NEXT_PUBLIC_COLOR_BORDER!,
  borderHover: process.env.NEXT_PUBLIC_COLOR_BORDER_HOVER!,
  borderFocus: process.env.NEXT_PUBLIC_COLOR_BORDER_FOCUS!,
  success: process.env.NEXT_PUBLIC_COLOR_SUCCESS!,
  successLight: process.env.NEXT_PUBLIC_COLOR_SUCCESS_LIGHT!,
  successDark: process.env.NEXT_PUBLIC_COLOR_SUCCESS_DARK!,
  error: process.env.NEXT_PUBLIC_COLOR_ERROR!,
  errorLight: process.env.NEXT_PUBLIC_COLOR_ERROR_LIGHT!,
  errorDark: process.env.NEXT_PUBLIC_COLOR_ERROR_DARK!,
  warning: process.env.NEXT_PUBLIC_COLOR_WARNING!,
  warningLight: process.env.NEXT_PUBLIC_COLOR_WARNING_LIGHT!,
  warningDark: process.env.NEXT_PUBLIC_COLOR_WARNING_DARK!,
  info: process.env.NEXT_PUBLIC_COLOR_INFO!,
  infoLight: process.env.NEXT_PUBLIC_COLOR_INFO_LIGHT!,
  infoDark: process.env.NEXT_PUBLIC_COLOR_INFO_DARK!,
});
